spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${global.server.host}:3306/watchdog
    username: watchdog
    password: watchdog
  redis:
    host: ${global.server.host}
    password: redis
    port: 6379
  rabbitmq:
    addresses: ${global.server.host}
    username: guest
    password: guest
  jpa:
    open-in-view: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: ${global.server.api}/docs
    enabled: true
global:
  server:
    dev: true
    encrypt:
      type: RSA
logging:
  level:
    i:
      watch: DEBUG
