global:
  server:
    name: StaticNote4K
    host: 127.0.0.1
    path: ${user.home}/.config/note
    api: /api
    api-path: ${global.server.api}
spring:
  profiles:
    active: prod
  cache:
    type: redis
