spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${global.server.data}:3306/watchdog
    username: watchdog
    password: watchdog
  redis:
    host: ${global.server.data}
    password: redis
    port: 6379
  rabbitmq:
    addresses: ${global.server.data}
    username: guest
    password: guest
  jpa:
    open-in-view: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: ${global.server.api}/docs
    enabled: true
global:
  server:
    dev: true
    encrypt:
      type: RSA
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnVjCUQai4H2cJcpVb7ZLZajsQuAWSB9fSG6x+JwWa9E43+H6nQ+qG/0wQdAU3UcOAWQ/Jf+tHcbHaXHgvyMHUhzzzaK7kElcZeLVHY4zfVoKJWASt4I9iCx8sl3v0FqVjGT75wTu3xNDPXXpK3IILGU+f4DClZ+oqo1DHqoyyOpNdo+PEBQen6fcJ0b2Rg4qtwuwQ81h11gQfcD51m2rXZi6xuu0pYXkEpaC5+XL/i594J9bHTuhwOYLDi0f87qeh5BL8zpOjnLlMMUmWrJc8lW9P+3YAkAKGH7wem3RjYEIoLxftWKBcANlUtnAzSkLDIKq+mgKVsW0aYdKobJqCwIDAQAB
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdWMJRBqLgfZwlylVvtktlqOxC4BZIH19IbrH4nBZr0Tjf4fqdD6ob/TBB0BTdRw4BZD8l/60dxsdpceC/IwdSHPPNoruQSVxl4tUdjjN9WgolYBK3gj2ILHyyXe/QWpWMZPvnBO7fE0M9dekrcggsZT5/gMKVn6iqjUMeqjLI6k12j48QFB6fp9wnRvZGDiq3C7BDzWHXWBB9wPnWbatdmLrG67SlheQSloLn5cv+Ln3gn1sdO6HA5gsOLR/zup6HkEvzOk6OcuUwxSZaslzyVb0/7dgCQAoYfvB6bdGNgQigvF+1YoFwA2VS2cDNKQsMgqr6aApWxbRph0qhsmoLAgMBAAECggEAIC3V17JOvzCRLZ1aqbUTaGAKqYagp/FakDqrRRfO8g/g3NCfa12XwY+fPeZrTfHJKHmy/Hd0lSFhCOyUNSLZzW5EYirExzZpoiCoyxmY6Crw5kHmsgb9xIqsmeHiOK895G+GoPF+VLrgxoIFxK/WghXWmUbhBK6ZVP/82Rmftzz5EsSS3WVso0Y/dqKDbWLx6dMdZt+zDf+HihkMesfwXnbCP18NHNs1LwWIfabgN04XIfSuCZOqrfFUBtbFJGamo1O5e+kcqWEYh9VpqBPsJ0fZJgsOjrzBa7h3mM8V57G65vn74xjrY2aq/TGvI5sgpUYr0hreGFWdt4bxbKF3mQKBgQDi5QokduMguizemMTDFpcKgQnFGSyfDh/7Z+dxBNQAfxytDr48E3NHfE3wlquZTqYoYnC003SPqcRI6FabSTxjeQMOhXahqAB8Gnmvc7mKYgYwXBVdb9GENnRSl6za35wUhC+1PncL4X9VslriBUaVyz1arY4rAMDovjamuSUtbQKBgQCxh9gWzm/tIdbZLEu5mG7UoshYpiqIMT8ohHKhcTGMpRYGnJdabqehdAXr0TrZlGxrkmTRX5OcHan7StuoExIVqLi8FtP0+ZcG/WOizeHg9h1ikOibY9wFe3m8U4IhH8bXGpp6WX1zrcNBk5v0F1E3HUU3Y2UvegJPw3HuzvWiVwKBgHddo55XZVocV+qrWCiCQ+fkxu0IN29eEPlESoAs2BOCy+VHclFMskMTZDWELrayp7trPnwDGrlRyM/KW3XKa5ixWyhSknytU8P2cboaGaxxsWvTpfHIF+OEemHRJcDoDsbEXAzv1dVMRp8g+6sYt2+qwpZn4/k/pj1LhJjlomdpAoGAeCHwvB4d512KwZMT+xeHiCRPZo2rIlYQ4x4dY9nxKbdc3ESCtxNCJCMbDqSbKjkh1PlPd88xV+dK612Qnn+pMTbnK4BXFeL/rB8zmSuwukZRRC3C+cPtU1hm3GW2HSwfpde+ySRdnDXtdyan1dkhgCYyfHSqOCJcBhW/t1YdKikCgYEApX6QpGXzheobdSTBB2hN2+AW0T84Q1QplvzGFF2Xi0WyBsvAA/U27eb51LS8HG139AE55V4r4Tjf8W/XxDV5MLwSh/0QIHz0U0xRAIGnKCY3BXaPYIy0wPqwkYDXpuoEhf1H358Z/QrGkZxBoLdWlOjZsBqtHNOM/GtKYwKfoVE=
logging:
  level:
    i:
      watch: DEBUG
