global:
  server:
    name: web-dog # 此名称不要轻易变更！密码加盐使用！
    host: 127.0.0.1
    data: 127.0.0.1
    api: /api
    dev: false
spring:
  profiles:
    active: prod
  application:
    name: ${global.server.name}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
