global:
  server:
    name: WatchDog4K
    host: 127.0.0.1
    api: /api
    dev: false
spring:
  profiles:
    active: prod
  application:
    name: ${global.server.name}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
